# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jonathan Hawley
tagline:          'The Skill Stacked Software Engineer'
description:      'The Skill Stacked Software Engineer'
url:              https://www.jdhawley.com
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Jonathan Hawley'
  url:            https://twitter.com/jdhawl

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"

future: false
show_drafts: false