# Site settings
name: Jonathan Hawley
email: jdhawley@crimson.ua.edu
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, C#, .NET, ASP.NET, .NET Core, ASP.NET Core, RabbitMQ, SQL Server, MS SQL Server, HTML, CSS, JavaScript, JS, Bootstrap, jQuery, SSIS, SSRS, SQL Server Integration Services, SQL Server Reporting Services, MS SQL Server Integration Services, MS SQL Server Reporting Services"
skills: ".NET Developer with a passion for teaching"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jdhawley/
  - title: github
    url: https://github.com/jdhawley
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
